application: hungphongbk-k2012-02
version: 2
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /bkstuinfo
  script: bk.stuinfo.app

- url: /bkstuinfo/.*
  script: bk.stuinfo.app


libraries:
- name: webapp2
  version: latest
- name: lxml
  version: latest
