application: hungphongbk-k2012-02
version: 2
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /bkstuinfo
  script: bk.stuinfo.app

- url: /bkstuinfo/.*
  script: bk.stuinfo.app

#- url: /stats.*
#  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py


libraries:
- name: webapp2
  version: latest
- name: lxml
  version: latest

#admin_console:
#  pages:
#  - name: Appstats
#    url: /stats